/**
 * @description parse html
 * @author wangfupeng
 */

import { IDomEditor } from '@wangeditor-next/core'
import { Descendant } from 'slate'

import $, { Dom7Array, DOMElement } from '../utils/dom'
import { styleStringToObject } from '../utils/util'
import { normalizeVideoAlign } from './alignment'
import { VideoAlign, VideoElement, videoStyle } from './custom-types'

function genVideoElem(
  src: string,
  poster = '',
  width = 'auto',
  height = 'auto',
  style: videoStyle = {},
  align: VideoAlign = 'center',
): VideoElement {
  return {
    type: 'video',
    src,
    poster,
    width,
    height,
    style,
    children: [{ text: '' }], // void 元素有一个空 text
    align,
  }
}

function getClassAlign($elem: Dom7Array): string {
  const classAttr = $elem.attr('class') || ''
  const classList = classAttr.trim().split(/\s+/).filter(Boolean)

  for (let i = 0; i < classList.length; i += 1) {
    const className = classList[i]

    if (className.startsWith('w-e-video-align-')) {
      return className.replace('w-e-video-align-', '')
    }
  }

  return ''
}

function getVideoAlign($elem: Dom7Array): VideoAlign {
  const dataAlign = ($elem.attr('data-w-e-align') || '').trim()

  if (dataAlign) { return normalizeVideoAlign(dataAlign) }

  const containerStyle = styleStringToObject($elem.attr('style') || '')
  const justifyContent = containerStyle['justify-content']

  if (justifyContent === 'flex-start') { return 'left' }
  if (justifyContent === 'flex-end') { return 'right' }
  if (justifyContent === 'center') { return 'center' }

  const classAlign = getClassAlign($elem)

  if (classAlign) { return normalizeVideoAlign(classAlign) }

  // Import-only adapters for HTML generated by the previous text-alignment model.
  const legacyStyleAlign = containerStyle['text-align']
  const legacyDataAlign = ($elem.attr('data-w-e-text-align') || '').trim()

  return normalizeVideoAlign(legacyStyleAlign || legacyDataAlign)
}

function getVideoSizeStyle(styleStr: string): videoStyle {
  const parsedStyle = styleStringToObject(styleStr) as Record<string, string>
  const style: videoStyle = {}

  if (parsedStyle.width) { style.width = parsedStyle.width }
  if (parsedStyle.height) { style.height = parsedStyle.height }

  return style
}

function parseHtml(elem: DOMElement, _children: Descendant[], _editor: IDomEditor): VideoElement {
  const $elem = $(elem)
  let src = ''
  let poster = ''
  let width = 'auto'
  let height = 'auto'
  let style: videoStyle = {}
  let align: VideoAlign = 'center'
  // <iframe> 形式
  const $iframe = $elem.find('iframe')

  if ($iframe.length > 0) {
    width = $iframe.attr('width') || 'auto'
    height = $iframe.attr('height') || 'auto'
    const iframeStyleStr = $iframe.attr('style') || ''

    style = getVideoSizeStyle(iframeStyleStr)
    const iframeStyleWidth = $iframe.attr('data-w-e-style-width') || ''
    const iframeStyleHeight = $iframe.attr('data-w-e-style-height') || ''

    if (!style.width && iframeStyleWidth) { style.width = iframeStyleWidth }
    if (!style.height && iframeStyleHeight) { style.height = iframeStyleHeight }
    src = $iframe[0].outerHTML
    align = getVideoAlign($elem)
    return genVideoElem(src, poster, width, height, style, align)
  }

  // <video> 形式
  const $video = $elem.find('video')

  src = $video.attr('src') || ''
  if (!src) {
    if ($video.length > 0) {
      const $source = $video.find('source')

      src = $source.attr('src') || ''
    }
  }
  width = $video.attr('width') || 'auto'
  height = $video.attr('height') || 'auto'
  poster = $video.attr('poster') || ''
  const videoStyleStr = $video.attr('style') || ''

  style = getVideoSizeStyle(videoStyleStr)
  const videoStyleWidth = $video.attr('data-w-e-style-width') || ''
  const videoStyleHeight = $video.attr('data-w-e-style-height') || ''

  if (!style.width && videoStyleWidth) { style.width = videoStyleWidth }
  if (!style.height && videoStyleHeight) { style.height = videoStyleHeight }
  align = getVideoAlign($elem)
  return genVideoElem(src, poster, width, height, style, align)
}

export const parseHtmlConf = {
  selector: 'figure[data-w-e-type="video"],div[data-w-e-type="video"]',
  parseElemHtml: parseHtml,
}
