name: coverage test

on:
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/*'
      - 'packages/**'
      - 'tests/**'
      - 'build/**'
      - 'vitest.config.mts'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # 检出代码库
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 设置 Node.js 版本
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.com

      # 安装 pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      # 加载依赖缓存
      - name: Load cached dependencies
        uses: actions/cache@v4.2.3
        id: cache
        with:
          path: |
            **/node_modules
            **/.turbo
            /home/runner/.cache/Cypress
            ~/.pnpm-store
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      # 安装依赖
      - name: Install dependencies
        run: pnpm install

      # 构建项目
      - name: Build packages
        run: pnpm build

      # 运行单元测试并生成覆盖率报告
      - name: Unit test
        run: pnpm run test-c

      # 上传覆盖率报告到 Codecov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5.4.3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
