name: Cypress tests

on:
  push:
    branches:
      - 'master'
      - 'dev'
      - '^(dev-.*|dev/.*)$'
      - '^(feature-.*|feature/.*)$'
      - '^(fix-.*|fix/.*)$'
      - '^(hotfix-.*|hotfix/.*)$'
      - '^(refactor-.*|refactor/.*)$'
      - '^(test-.*|test/.*)$'
    paths:
      - '.github/workflows/*'
      - 'packages/**'
      - 'scripts/**'
      - 'tests/**'
      - 'build/**'
      - 'cypress/**'
      - 'babel.config.json'
      - 'cypress.json'
  pull_request:
    branches:
      - master

jobs:
  test-e2e:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:latest
      options: --user 1001
    steps:
      - uses: actions/checkout@v4

      # 设置 Node.js 版本
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 安装 pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      # 加载依赖缓存
      - name: Load cached dependencies
        uses: actions/cache@v4.2.3
        id: cache
        with:
          path: |
            **/node_modules
            **/.turbo
            /home/runner/.cache/Cypress
            ~/.pnpm-store
          key: ${{ runner.os }}-node-18-${{ hashFiles('**/pnpm-lock.yaml') }}


      # 安装项目依赖
      - name: Install dependencies
        run: pnpm install

      # 构建项目
      - name: Build packages
        run: pnpm build

      # 运行 Cypress 测试
      - uses: cypress-io/github-action@v6
        with:
          install: false
          browser: chrome
          start: pnpm run example
          wait-on: 'http://localhost:8881/examples/default-mode.html'
