name: Release

on:
  push:
    branches:
      - master
      - develop
      - '^(dev-.*|dev/.*)$'
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]

    steps:
      # 检出代码库
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 设置 Node.js 版本
      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version:  ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org/'

      # 安装 pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      # 加载依赖缓存
      - name: Load cached dependencies
        uses: actions/cache@v4.2.3
        id: cache
        with:
          path: |
            **/node_modules
            **/.turbo
            /home/runner/.cache/Cypress
            ~/.pnpm-store
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package.json', '**/pnpm-lock.yaml') }}

      # 安装依赖
      - name: Install dependencies
        run: pnpm install

      # 构建项目
      - name: Build packages
        run: pnpm build

      # 运行单元测试
      - name: Unit test
        run: pnpm run test

      # 运行 E2E 测试
      - name: E2E test
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          start: pnpm run example
          wait-on: 'http://localhost:8881/examples/default-mode.html'

      # 创建测试版本或稳定版本的 Release PR
      - name: Manage Changeset Pre-release Mode
        if: startsWith(github.ref_name, 'dev') || github.ref_name == 'develop'
        run: pnpm changeset pre enter alpha || true

      - name: Exit Changeset Pre-release Mode
        if: github.ref_name == 'master'
        run: pnpm changeset pre exit || true

      - name: Create Release PR or publish version to npm
        id: changesets
        uses: changesets/action@v1
        with:
          createGithubReleases: false
          publish: pnpm changeset publish --access=public
          title: >-
            ${{ github.ref_name == 'master' && 'Publish a new stable version' || 'Publish a new pre-release version' }}
          commit: >-
            ${{ github.ref_name == 'master' && 'chore(release): publish a new release version' || 'chore(release): publish a new pre-release version' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # 发布 GitHub Release
      - name: Publish GitHub Release for editor
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')

